services:
  - type: web
    name: Music
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y --no-install-recommends ffmpeg && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* && \
      pip3 install --no-cache-dir -U -r requirements.txt
    startCommand: 'bash start'
    plan: free